[
    ["ACE_bloodIV", ["Medic", "Crewman", "Pilot"], []],
    ["ACE_bloodIV_500", ["Medic", "Crewman", "Pilot"], []],
	["ACE_plasmaIV_500", ["Medic", "Crewman", "Pilot"], []],
	["ACE_epinephrine", [], []],
    ["kat_fentanyl", ["Medic", "Crewman", "Pilot"], []],
	["kat_naloxone", ["Medic", "Crewman", "Pilot"], []],
    ["kat_oxygenTank_300_item", ["Medic", "Crewman", "Pilot"], []],
	["kat_BVM", ["Medic", "Crewman", "Pilot"], []],
    ["kat_chestseal", ["Medic", "Crewman", "Pilot"], []],
	["ACE_surgicalKit", ["Medic", "Crewman", "Pilot"], []],
    ["kat_Pulseoximeter", ["Medic", "Crewman", "Pilot"], []],
	["kat_atropine", ["Medic", "Crewman", "Pilot"], []],
    ["kat_accuvac", ["Medic", "Crewman", "Pilot"], []],
	["kat_larynx", ["Medic", "Crewman", "Pilot"], []],
    ["kat_AED", ["Medic", "Crewman", "Pilot"], []],
	["KAT_Empty_bloodIV_500", ["Medic", "Crewman", "Pilot"], []],
    ["KAT_Katmin", ["Medic", "Crewman", "Pilot"], []],
	["ACE_splint", [], []],
    ["kat_Pervitin", [], []],
	["ACE_elasticBandage", [], []],
	["ACE_packingBandage", [], []],
	["ACE_quikclot", [], []],
	["ACE_tourniquet", [], []],
	["kat_Painkiller", [], []],
	["ACE_morphine", ["Medic", "Crewman", "Pilot"], []]
]