[
	["rtg_NV_RTG_Armband_F", [], []],
    ["rtg_NV_RTG_Armband_alt_F", [], []],
    ["TFAR_anprc152", [], []],
    ["ACE_bodyBag", [], []],
	["ACE_CableTie", [], []],
	["ACE_EntrenchingTool", [], []],
    ["ACE_IR_Strobe_Item", [], []],
	["ACE_Flashlight_XL50", [], []],
    ["ACE_MapTools", [], []],
	["ACE_SpraypaintGreen", [], []],
    ["ACE_SpraypaintRed", [], []],
	["ACE_SpraypaintBlue", [], []],
    ["ACE_SpraypaintYellow", [], []],
	["itemMap", [], []],
    ["Laserbatteries", [], []],
	["iedd_item_notebook", [], []],
    ["KAT_ChemicalDetector", [], []],
	["kat_mask_M04", [], []],
    ["kat_gasmaskFilter", [], []],
	["Binocular", [], []],
	["ACE_microDAGR", [], []],
    ["itemGPS", [], []],
	["itemCompass", [], []],
    ["itemWatch", [], []],
	["cigs_Apollo_cigpack", [], []],
	["cigs_cigars_cigarbox_5", [], []],
	["cigs_lighter", [], []],
	["cigs_pops_poppack", [], []],
	["cigs_matches", [], []],
	["cigs_crayons_crayonpack", [], []],
	["cigs_Voron_cigpack", [], []],
	["cigs_morley_cigpack", [], []],
	["cigs_Kosmos_cigpack", [], []],
	["cigs_craven_cigpack", [], []],
	["slr_slingload_CargoSling", ["Combat Engineer", "Pointman"], []],
	["ACE_DefusalKit", ["Combat Engineer", "Pointman"], []],
	["MineDetector", ["Combat Engineer", "Pointman"], []],
	["ACE_rope6", ["Combat Engineer", "Pointman"], []],
	["ACE_wirecutter", [], []],
	["rhsusf_m112_mag", ["Combat Engineer"], []],
	["tsp_breach_stick_mag", ["Combat Engineer"], []],
	["SLAMDirectionalMine_Wire_Mag", ["Combat Engineer"], []],
	["ACE_CTS9", ["Combat Engineer"], []],
	["tsp_breach_package_mag", ["Combat Engineer"], []],
	["ACE_Clacker", ["Combat Engineer"], []],
    ["rtg_thermalSighting_System", ["Rifleman", "Light Rifleman", "Pointman"], []],
	["Binocular", [], []],
	["rtg_LaserDesignator_tan_ah", ["Rifleman", "Light Rifleman", "Pointman", "Team Leader", "Crewman", "Pilot"], []],
	["rtg_LaserDesignator_tan_gh", ["Rifleman", "Light Rifleman", "Pointman", "Team Leader", "Crewman", "Pilot"], []],
	["rtg_LaserDesignator_tan_wh", ["Rifleman", "Light Rifleman", "Pointman", "Team Leader", "Crewman", "Pilot"], []],
	["rtg_LaserDesignator_grn_ah", ["Rifleman", "Light Rifleman", "Pointman", "Team Leader", "Crewman", "Pilot"], []],
	["rtg_LaserDesignator_grn_gh", ["Rifleman", "Light Rifleman", "Pointman", "Team Leader", "Crewman", "Pilot"], []],
	["rtg_LaserDesignator_grn_wh", ["Rifleman", "Light Rifleman", "Pointman", "Team Leader", "Crewman", "Pilot"], []],

// CSW
	["ACE_SpareBarrel", ["Ammo Bearer"], []],
	// Weapons
	["ace_csw_staticATCarry", ["CSW Gunner"], []],
	["ace_csw_staticHMGCarry", ["CSW Gunner"], []],
	// Tripods
	["ace_csw_m3CarryTripod", ["Ammo Bearer"], []],
	["ace_csw_m3CarryTripodLow", ["Ammo Bearer"], []],
	// Ammo
	["RTG_100Rnd_127x99_SLAP_CSW", ["Ammo Bearer", "Team Leader", "CSW Gunner"], []],
	["RTG_TOW3A_CSW", ["Ammo Bearer", "Team Leader", "CSW Gunner"], []],
	["RTG_TOW3BB_CSW", ["Ammo Bearer", "Team Leader", "CSW Gunner"], []]
]