[
// GLs
	["GL_XM25_F", ["Grenadier"], []],
	["GL_M32_F", ["Grenadier"], []],
	["ptv_L2F", ["Grenadier"], []],
	["ptv_L2F_g", ["Grenadier"], ["WDL", "ARD", "TUN"]],
	["ptv_L2F_t", ["Grenadier"], ["ARD", "DES"]],
	["glaunch_GLX_lxWS", ["Grenadier"], []],
	["glaunch_GLX_olive_lxWS", ["Grenadier"], ["WDL", "ARD", "TUN"]],
	["glaunch_GLX_sand_lxWS", ["Grenadier"], ["ARD", "DES"]],

// Rifles
	["ICM_XM7_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["ICM_XM7_F_Arid", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["ICM_XM7_F_Khaki", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["ICM_XM7_F_CTRG_Tropic", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["ICM_XM7_F_CTRG_Arid", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["JCA_arifle_M4a1_Black_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["JCA_arifle_M4a1_olive_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["JCA_arifle_M4a1_Sand_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["JCA_arifle_M4a1_GL_Black_F", ["Grenadier", "Team Leader"], []],
	["JCA_arifle_M4a1_GL_olive_F", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["JCA_arifle_M4a1_GL_Sand_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["JCA_arifle_m16A4_Black_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["JCA_arifle_m16A4_olive_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["JCA_arifle_m16A4_Sand_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["JCA_arifle_m16A4_FG_Black_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["JCA_arifle_m16A4_FG_olive_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["JCA_arifle_m16A4_FG_Sand_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["JCA_arifle_m16A4_GL_Black_F", ["Grenadier", "Team Leader"], []],
	["JCA_arifle_m16A4_GL_olive_F", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["JCA_arifle_m16A4_GL_Sand_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["arifle_Mk20_black_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_Mk20_plain_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_Mk20_gl_black_F", ["Grenadier", "Team Leader"], []],
	["arifle_Mk20_gl_plain_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["arifle_Katiba_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_Katiba_GL_F", ["Grenadier", "Team Leader"], []],
	["arifle_MX_Black_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_MX_khk_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_MX_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["ef_arifle_MXar_Black", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["ef_arifle_MXar_khk", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["ef_arifle_MXar", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["ef_arifle_MXar_GL_Black", ["Grenadier", "Team Leader"], []],
	["ef_arifle_MXar_GL_khk", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["ef_arifle_MXar_GL", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["arifle_MX_GL_Black_F", ["Grenadier", "Team Leader"], []],
	["arifle_MX_GL_khk_F", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["arifle_MX_GL_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["srifle_EBR_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], []],
	["srifle_EBR_blk_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], []],
	["srifle_EBR_khk_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["srifle_EBR_cbr_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], ["ARD", "DES"]],
	["srifle_DMR_01_black_RF", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], []],
	["srifle_DMR_01_tan_RF", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], ["ARD", "DES"]],
	["arifle_TRG21_black_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_TRG21_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_TRG21_GL_black_F", ["Grenadier", "Team Leader"], []],
	["arifle_TRG21_GL_F", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["arifle_SA80_blk_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_SA80_khk_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_SA80_snd_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_SA80_GL_blk_F", ["Grenadier", "Team Leader"], []],
	["arifle_SA80_GL_khk_F", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["arifle_SA80_GL_snd_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["arifle_SCAR_L_black_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_SCAR_L_khaki_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_SCAR_L_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_SCAR_L_grip_black_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_SCAR_L_grip_khaki_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_SCAR_L_grip_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_SCAR_black_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], []],
	["arifle_SCAR_khaki_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["arifle_SCAR_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], ["ARD", "DES"]],
	["arifle_SCAR_grip_black_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], []],
	["arifle_SCAR_grip_khaki_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["arifle_SCAR_grip_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], ["ARD", "DES"]],
	["Aegis_arifle_SR25_blk_F", ["Ammo Bearer", "CSW Gunner", "Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], []],
	["Aegis_arifle_SR25_khk_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["Aegis_arifle_SR25_snd_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], ["ARD", "DES"]],
	["Aegis_arifle_SVD_blk_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], []],
	["Aegis_arifle_SVD_plum_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], []],
	["Aegis_arifle_SVD_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], []],
	["Aegis_arifle_SPAR_02_inf_blk_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["Aegis_arifle_SPAR_02_inf_khk_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["Aegis_arifle_SPAR_02_inf_snd_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_ARX_blk_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["atlas_arifle_famasF1_RIS_F", ["Automatic Rifleman","Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["atlas_arifle_famasF1_Grip_F", ["Automatic Rifleman","Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["atlas_arifle_famasF1_GL_F", ["Grenadier", "Team Leader"], []],
	["atlas_arifle_famasG2_F", ["Automatic Rifleman","Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["atlas_arifle_famasG2_Grip_F", ["Automatic Rifleman","Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["atlas_arifle_famasG2_GL_F", ["Grenadier", "Team Leader"], []],
	["arifle_AUG_black_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_AUG_GL_black_F", ["Grenadier", "Team Leader"], []],
	["arifle_AUG_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_AUG_GL_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["atlas_arifle_famasG4_Grip_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["atlas_arifle_famasG4_GL_F", ["Grenadier", "Team Leader"], []],
	["arifle_G36_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_G36_GL_F", ["Grenadier", "Team Leader"], []],
	["arifle_G36_Sand_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_G36_GL_Sand_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["arifle_ash12_blk_RF", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_ash12_wood_RF", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_ash12_desert_RF", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_ash12_LR_blk_RF", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_ash12_LR_wood_RF", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_ash12_LR_desert_RF", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_ash12_GL_blk_RF", ["Grenadier", "Team Leader"], []],
	["arifle_ash12_GL_wood_RF", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["arifle_ash12_GL_desert_RF", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["arifle_SLR_V_lxws", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], []],
	["arifle_SLR_lxws", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], []],
	["arifle_SLR_Para_lxws", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], []],
	["arifle_SLR_V_Camo_lxws", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["arifle_SLR_D_lxws", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader"], ["ARD", "DES"]],
	["arifle_XMS_lxws", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_XMS_Gray_lxws", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_XMS_khk_lxws", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_XMS_sand_lxws", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_XMS_GL_lxws", ["Grenadier", "Team Leader"], []],
	["arifle_XMS_GL_Gray_lxws", ["Grenadier", "Team Leader"], []],
	["arifle_XMS_GL_khk_lxws", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["Aegis_arifle_AK103_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["Aegis_arifle_AK103_plum_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["Aegis_arifle_AK103_GL_F", ["Grenadier", "Team Leader"], []],
	["Aegis_arifle_AK103_GL_plum_F", ["Grenadier", "Team Leader"], []],
	["Aegis_arifle_AK74_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["Aegis_arifle_AK74_oak_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["Aegis_arifle_AK74S_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["Aegis_arifle_AK74S_oak_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["Aegis_arifle_AK74_GL_F", ["Grenadier", "Team Leader"], []],
	["Aegis_arifle_AK74_GL_oak_F", ["Grenadier", "Team Leader"], []],
	["Aegis_arifle_AK74M_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["Aegis_arifle_AK74M_plum_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["Aegis_arifle_AK74M_olive_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["Aegis_arifle_AK74M_sand_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["Aegis_arifle_AK74M_GL_F", ["Grenadier", "Team Leader"], []],
	["Aegis_arifle_AK74M_GL_plum_F", ["Grenadier", "Team Leader"], []],
	["Aegis_arifle_AK74M_GL_olive_F", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["Aegis_arifle_AK74M_GL_sand_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["arifle_AK12_545_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_AK12_545_lush_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_AK12_545_tan_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_AK12_545_GL_F", ["Grenadier", "Team Leader"], []],
	["arifle_AK12_545_GL_lush_F", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["arifle_AK12_545_GL_tan_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["arifle_MSBS65_black_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_MSBS65_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_MSBS65_sand_F", ["Ammo Bearer", "CSW Gunner", "Rifleman", "Light Rifleman",  "Pointman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_MSBS65_GL_black_F", ["Grenadier", "Team Leader"], []],
	["arifle_MSBS65_GL_F", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["arifle_MSBS65_GL_sand_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	
// Carbines
	["arifle_Katiba_C_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_Mk20c_black_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_Mk20c_plain_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_MXC_Black_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_MXC_khk_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_MXC_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["JCA_arifle_M4a4_AFG_Black_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["JCA_arifle_M4a4_AFG_olive_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["JCA_arifle_M4a4_AFG_Sand_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["JCA_arifle_M4a4_VFG_Black_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["JCA_arifle_M4a4_VFG_olive_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["JCA_arifle_M4a4_VFG_Sand_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["JCA_arifle_M4a1_short_Black_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["JCA_arifle_M4a1_short_olive_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["JCA_arifle_M4a1_short_Sand_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["JCA_arifle_M4a4_GL_Black_F", ["Grenadier", "Team Leader"], []],
	["JCA_arifle_M4a4_GL_olive_F", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["JCA_arifle_M4a4_GL_Sand_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["arifle_TRG20_black_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_TRG20_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_SA80_C_blk_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_SA80_C_khk_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_SA80_C_snd_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_SCAR_L_short_black_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_SCAR_L_short_khaki_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_SCAR_L_short_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_SCAR_L_GL_black_F", ["Grenadier", "Team Leader"], []],
	["arifle_SCAR_L_GL_khaki_F", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["arifle_SCAR_L_GL_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["arifle_SCAR_short_black_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_SCAR_short_khaki_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_SCAR_short_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_SCAR_GL_black_F", ["Grenadier", "Team Leader"], []],
	["arifle_SCAR_GL_khaki_F", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["arifle_SCAR_GL_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["arifle_SPAR_01_blk_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_SPAR_01_khk_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_SPAR_01_snd_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_SPAR_01_GL_blk_F", ["Grenadier", "Team Leader"], []],
	["arifle_SPAR_01_GL_khk_F", ["Grenadier", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["arifle_SPAR_01_GL_snd_F", ["Grenadier", "Team Leader"], ["ARD", "DES"]],
	["arifle_AUG_C_black_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_AUG_C_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_G36C_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_G36C_Sand_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	["arifle_AK12U_545_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], []],
	["arifle_AK12U_545_lush_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["WDL", "ARD", "TUN"]],
	["arifle_AK12U_545_tan_F", ["Combat Engineer", "Pilot", "Crewman", "Team Leader", "Medic", "Rocket Grenadier", "Medium Anti-Tank", "Heavy Anti-Tank"], ["ARD", "DES"]],
	

// SMGS 
	["hgun_PDW2000_F", ["Combat Engineer", "Pilot", "Crewman"], []],
	["JCA_smg_MP5_FL_Black_F", ["Combat Engineer", "Pilot", "Crewman"], []],
	["JCA_smg_MP5_FL_olive_F", ["Combat Engineer", "Pilot", "Crewman"], ["WDL", "ARD", "TUN"]],
	["JCA_smg_MP5_FL_Sand_F", ["Combat Engineer", "Pilot", "Crewman"], ["ARD", "DES"]],
	["JCA_smg_MP5_AFG_Black_F", ["Combat Engineer", "Pilot", "Crewman"], []],
	["JCA_smg_MP5_AFG_olive_F", ["Combat Engineer", "Pilot", "Crewman"], ["WDL", "ARD", "TUN"]],
	["JCA_smg_MP5_AFG_Sand_F", ["Combat Engineer", "Pilot", "Crewman"], ["ARD", "DES"]],
	["JCA_smg_MP5_VFG_Black_F", ["Combat Engineer", "Pilot", "Crewman"], []],
	["JCA_smg_MP5_VFG_olive_F", ["Combat Engineer", "Pilot", "Crewman"], ["WDL", "ARD", "TUN"]],
	["JCA_smg_MP5_VFG_Sand_F", ["Combat Engineer", "Pilot", "Crewman"], ["ARD", "DES"]],
	["JCA_smg_UMP_Black_F", ["Combat Engineer", "Pilot", "Crewman"], []],
	["JCA_smg_UMP_olive_F", ["Combat Engineer", "Pilot", "Crewman"], ["WDL", "ARD", "TUN"]],
	["JCA_smg_UMP_Sand_F", ["Combat Engineer", "Pilot", "Crewman"], ["ARD", "DES"]],
	["JCA_smg_UMP_AFG_Black_F", ["Combat Engineer", "Pilot", "Crewman"], []],
	["JCA_smg_UMP_AFG_olive_F", ["Combat Engineer", "Pilot", "Crewman"], ["WDL", "ARD", "TUN"]],
	["JCA_smg_UMP_AFG_Sand_F", ["Combat Engineer", "Pilot", "Crewman"], ["ARD", "DES"]],
	["JCA_smg_UMP_VFG_Black_F", ["Combat Engineer", "Pilot", "Crewman"], []],
	["JCA_smg_UMP_VFG_olive_F", ["Combat Engineer", "Pilot", "Crewman"], ["WDL", "ARD", "TUN"]],
	["JCA_smg_UMP_VFG_Sand_F", ["Combat Engineer", "Pilot", "Crewman"], ["ARD", "DES"]],
	["SMG_04_blk_F", ["Combat Engineer", "Pilot", "Crewman"], []],
	["SMG_04_khk_F", ["Combat Engineer", "Pilot", "Crewman"], ["WDL", "ARD", "TUN"]],
	["SMG_04_snd_F", ["Combat Engineer", "Pilot", "Crewman"], ["ARD", "DES"]],
	["SMG_01_black_F", ["Combat Engineer", "Pilot", "Crewman"], []],
	["SMG_01_khk_F", ["Combat Engineer", "Pilot", "Crewman"], ["WDL", "ARD", "TUN"]],
	["SMG_01_F", ["Combat Engineer", "Pilot", "Crewman"], ["ARD", "DES"]],

// ARs 
	["Aegis_arifle_RPK74M_F", ["Automatic Rifleman"], []],
	["Aegis_arifle_RPK12_545_F", ["Automatic Rifleman"], []],
	["Aegis_arifle_RPK12_545_lush_F", ["Automatic Rifleman"], ["WDL", "ARD", "TUN"]],
	["Aegis_arifle_RPK12_545_tan_F", ["Automatic Rifleman"], ["ARD", "DES"]],
	["arifle_XMS_M_lxws", ["Automatic Rifleman"], []],
	["arifle_XMS_M_Gray_lxws", ["Automatic Rifleman"], []],
	["arifle_XMS_M_khk_lxws", ["Automatic Rifleman"], ["WDL", "ARD", "TUN"]],
	["arifle_XMS_M_sand_lxws", ["Automatic Rifleman"], ["ARD", "DES"]],
	["LMG_03_F", ["Automatic Rifleman"], []],
	["LMG_03_khk_F", ["Automatic Rifleman"], ["WDL", "ARD", "TUN"]],
	["LMG_03_snd_F", ["Automatic Rifleman"], ["ARD", "DES"]],
	["LMG_Mk200_black_F", ["Automatic Rifleman"], []],
	["LMG_Mk200_khk_F", ["Automatic Rifleman"], ["WDL", "ARD", "TUN"]],
	["LMG_Mk200_plain_F", ["Automatic Rifleman"], ["ARD", "DES"]],
	["arifle_MX_SW_Black_F", ["Automatic Rifleman"], []],
	["arifle_MX_SW_khk_F", ["Automatic Rifleman"], ["WDL", "ARD", "TUN"]],
	["arifle_MX_SW_F", ["Automatic Rifleman"], ["ARD", "DES"]],
	["ef_arifle_mx_sw_coy", ["Automatic Rifleman"], ["ARD", "DES"]],
	["arifle_SPAR_02_blk_F", ["Automatic Rifleman"], []],
	["arifle_SPAR_02_khk_F", ["Automatic Rifleman"], ["WDL", "ARD", "TUN"]],
	["arifle_SPAR_02_snd_F", ["Automatic Rifleman"], ["ARD", "DES"]],
	["Aegis_MMG_FNMAG_F", [ "Automatic Rifleman", "Machine Gunner"], []],
	["Aegis_MMG_FNMAG_240_F", [ "Automatic Rifleman", "Machine Gunner"], []],
	["Atlas_LMG_Negev_black_F", [ "Automatic Rifleman", "Machine Gunner"], []],
	["LMG_s77_lxws", [ "Automatic Rifleman", "Machine Gunner"], []],
	["LMG_s77_Compact_lxws", [ "Automatic Rifleman", "Machine Gunner"], []],
	["LMG_s77_Desert_lxws", [ "Automatic Rifleman", "Machine Gunner"], []],
	["ptv_m60e4", [ "Automatic Rifleman", "Machine Gunner"], []],
	["ptv_m60e4_g", [ "Automatic Rifleman", "Machine Gunner"], ["WDL", "ARD", "TUN"]],
	["ptv_m60e4_t", [ "Automatic Rifleman", "Machine Gunner"], ["ARD", "DES"]],
	["ptv_m60e4s", [ "Automatic Rifleman", "Machine Gunner"], []],
	["ptv_m60e4s_g", [ "Automatic Rifleman", "Machine Gunner"], ["WDL", "ARD", "TUN"]],
	["ptv_m60e4s_t", [ "Automatic Rifleman", "Machine Gunner"], ["ARD", "DES"]],
	["ptv_m60e4r", [ "Automatic Rifleman", "Machine Gunner"], []],
	["ptv_m60e4r_g", [ "Automatic Rifleman", "Machine Gunner"], ["WDL", "ARD", "TUN"]],
	["ptv_m60e4r_t", [ "Automatic Rifleman", "Machine Gunner"], ["ARD", "DES"]],
	["ptv_m60e4rs", [ "Automatic Rifleman", "Machine Gunner"], []],
	["ptv_m60e4rs_g", [ "Automatic Rifleman", "Machine Gunner"], ["WDL", "ARD", "TUN"]],
	["ptv_m60e4rs_t", [ "Automatic Rifleman", "Machine Gunner"], ["ARD", "DES"]],
	["ptv_ng5_b", [ "Automatic Rifleman"], []],
	["ptv_ng5", [ "Automatic Rifleman"], ["WDL", "ARD", "TUN"]],
	["MMG_02_black_F", ["Automatic Rifleman", "Machine Gunner"], []],
	["MMG_02_khaki_F", ["Automatic Rifleman", "Machine Gunner"], ["WDL", "ARD", "TUN"]],
	["MMG_02_sand_F", ["Automatic Rifleman", "Machine Gunner"], ["ARD", "DES"]],
	["ptv_MG3r", ["Automatic Rifleman", "Machine Gunner"], []],

// Shotguns
	["sgun_aa40_lxws", ["Combat Engineer"], []],
	["sgun_aa40_khk_lxws", ["Combat Engineer"], ["WDL", "ARD", "TUN"]],
	["sgun_aa40_tan_lxws", ["Combat Engineer"], ["ARD", "DES"]],
	["Aegis_sgun_KSG_black_F", ["Combat Engineer"], []],
	["Aegis_sgun_KSG_F", ["Combat Engineer"], ["WDL", "ARD", "TUN"]],
	["sgun_M4_F", ["Combat Engineer"], []],
	["sgun_Mp153_classic_F", ["Combat Engineer"], []],
	["sgun_Mp153_black_F", ["Combat Engineer"], []]
]