[
// Armour Crew
    ["lxWS_H_HelmetCrew_I", ["Crewman"], []],
    ["H_HelmetCrew_I", ["Crewman"], ["WDL", "ARD", "TUN"]],
	["H_HelmetCrew_I_I", ["Crewman"], ["ARD", "DES"]],
// Heli Crew
	["H_CrewHelmetHeli_B", ["Pilot"], []],
    ["H_CrewHelmetHeli_I_E", ["Pilot"], ["WDL", "ARD", "TUN"]],
	["H_CrewHelmetHeli_O", ["Pilot"], ["WDL", "ARD", "TUN"]],
	["H_PilotHelmetHeli_B", ["Pilot"], []],
    ["H_PilotHelmetHeli_I_E", ["Pilot"], ["WDL", "ARD", "TUN"]],
	["H_PilotHelmetHeli_O", ["Pilot"], ["WDL", "ARD", "TUN"]],
	["H_PilotHelmetHeli_B_Visor_UP", ["Pilot"], []],
    ["H_PilotHelmetHeli_I_E_Visor_UP", ["Pilot"], ["WDL", "ARD", "TUN"]],
	["H_PilotHelmetHeli_O_Visor_UP", ["Pilot"], ["WDL", "ARD", "TUN"]],
// Beanies
	["H_Watchcap_blk_hs", [], []],
    ["H_Watchcap_camo_hs", [], ["WDL", "ARD", "TUN"]],
	["H_Watchcap_cbr_hs", [], ["ARD", "DES"]],
// Boonies
	["H_Booniehat_blk", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], []],
    ["H_Booniehat_mgrn", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["WDL", "ARD", "TUN"]],
	["H_Booniehat_tan", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["ARD", "DES"]],
// Raven
	["H_HelmetSpecter_black_headset_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], []],
    ["H_HelmetSpecter_headset_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["WDL", "ARD", "TUN"]],
	["H_HelmetSpecter_brown_headset_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["ARD", "DES"]],
// AMH
	["JCA_H_HelmetHBK_headset_black_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], []],
	["JCA_H_HelmetHBK_ear_black_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], []],
	["JCA_H_HelmetHBK_chops_black_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], []],
    ["JCA_H_HelmetHBK_headset_olive_f", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["WDL", "ARD", "TUN"]],
	["JCA_H_HelmetHBK_ear_olive_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["WDL", "ARD", "TUN"]],
	["JCA_H_HelmetHBK_chops_olive_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["WDL", "ARD", "TUN"]],
	["JCA_H_HelmetHBK_headset_sand_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["ARD", "DES"]],
	["JCA_H_HelmetHBK_ear_sand_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["ARD", "DES"]],
	["JCA_H_HelmetHBK_chops_sand_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["ARD", "DES"]],
// Intruder
	["Atlas_H_HelmetCCH_HiCut_Headset_blk_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], []],
    ["Atlas_H_HelmetCCH_HiCut_Headset_grn_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["WDL", "ARD", "TUN"]],
	["Atlas_H_HelmetCCH_HiCut_Headset_khk_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["ARD", "DES"]],
// Liberator
	["Atlas_H_HelmetCCH_Headset_blk_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], []],
    ["Atlas_H_HelmetCCH_Headset_grn_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["WDL", "ARD", "TUN"]],
	["Atlas_H_HelmetCCH_Headset_khk_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["ARD", "DES"]],
// Operator
	["Aegis_H_Helmet_FASTMT_Headset_blk_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], []],
    ["Aegis_H_Helmet_FASTMT_Headset_rgr_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["WDL", "ARD", "TUN"]],
	["Aegis_H_Helmet_FASTMT_Headset_tan_F", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["ARD", "DES"]],
// MCH
	["EF_H_MCH_FullCamo_Black", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], []],
    ["EF_H_MCH_FullCamo_Olive", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["WDL", "ARD", "TUN"]],
	["EF_H_MCH_FullCamo_Coy", ["Automatic Rifleman", "Machine Gunner", "Rifleman","Grenadier","Rocket Grenadier", "Pointman", "Light Rifleman", "Combat Engineer", "Medium Anti-Tank", "Heavy Anti-Tank", "Team Leader", "Medic"], ["ARD", "DES"]],
// Light Heli Crew
	["H_PilotHelmetHeli_Black_RF", ["Pilot"], []],
    ["H_PilotHelmetHeli_Blue_RF", ["Pilot"], []],
	["H_PilotHelmetHeli_Green_RF", ["Pilot"], []],
	["H_PilotHelmetHeli_MilGreen_RF", ["Pilot"], []],
	["H_PilotHelmetHeli_Orange_RF", ["Pilot"], []],
	["H_PilotHelmetHeli_Red_RF", ["Pilot"], []],
	["H_PilotHelmetHeli_White_RF", ["Pilot"], []],
	["H_PilotHelmetHeli_Yellow_RF", ["Pilot"], []],

// CTRG Caps
	["CTRG_cap_01_Arid", [], ["ARD"]],
    ["CTRG_cap_01_goggles_Arid", [], ["ARD"]],
    ["CTRG_cap_02_Arid", [], ["ARD"]],
    ["CTRG_cap_02_goggles_Arid", [], ["ARD"]],
    ["CTRG_cap_03_Arid", [], ["ARD"]],
    ["CTRG_cap_03_goggles_Arid", [], ["ARD"]],

    ["CTRG_cap_01_Desert", [], ["DES"]],
    ["CTRG_cap_01_goggles_Desert", [], ["DES"]],
    ["CTRG_cap_02_Desert", [], ["DES"]],
    ["CTRG_cap_02_goggles_Desert", [], ["DES"]],
   	["CTRG_cap_03_Desert", [], ["DES"]],
    ["CTRG_cap_03_goggles_Desert", [], ["DES"]],

    ["CTRG_cap_01_Tundra", [], ["TUN"]],
    ["CTRG_cap_01_goggles_Tundra", [], ["TUN"]],
    ["CTRG_cap_02_Tundra", [], ["TUN"]],
    ["CTRG_cap_02_goggles_Tundra", [], ["TUN"]],
    ["CTRG_cap_03_Tundra", [], ["TUN"]],
    ["CTRG_cap_03_goggles_Tundra", [], ["TUN"]],

    ["CTRG_cap_01_Tropic", [], ["WDL"]],
    ["CTRG_cap_01_goggles_Tropic", [], ["WDL"]],
    ["CTRG_cap_02_Tropic", [], ["WDL"]],
    ["CTRG_cap_02_goggles_Tropic", [], ["WDL"]],
    ["CTRG_cap_03_Tropic", [], ["WDL"]],
    ["CTRG_cap_03_goggles_Tropic", [], ["WDL"]],

// CTRG Airframes
	["CTRG_Retexture_airframe_01_Arid", [], ["ARD"]],
    ["CTRG_Retexture_airframe_01_goggles_Arid", [], ["ARD"]],
   	["CTRG_Retexture_airframe_02_Arid", [], ["ARD"]],
    ["CTRG_Retexture_airframe_02_goggles_Arid", [], ["ARD"]],
    ["CTRG_Retexture_airframe_03_Arid", [], ["ARD"]],
    ["CTRG_Retexture_airframe_03_goggles_Arid", [], ["ARD"]],
	["CTRG_Retexture_airframe_04_Arid", [], ["ARD"]],
    ["CTRG_Retexture_airframe_04_goggles_Arid", [], ["ARD"]],
    ["CTRG_Retexture_airframe_05_Arid", [], ["ARD"]],
    ["CTRG_Retexture_airframe_05_goggles_Arid", [], ["ARD"]],
    ["CTRG_Retexture_airframe_06_Arid", [], ["ARD"]],
    ["CTRG_Retexture_airframe_06_goggles_Arid", [], ["ARD"]],

    ["CTRG_Retexture_airframe_01_Desert", [], ["DES"]],
    ["CTRG_Retexture_airframe_01_goggles_Desert", [], ["DES"]],
    ["CTRG_Retexture_airframe_02_Desert", [], ["DES"]],
    ["CTRG_Retexture_airframe_02_goggles_Desert", [], ["DES"]],
	["CTRG_Retexture_airframe_03_Desert", [], ["DES"]],
    ["CTRG_Retexture_airframe_03_goggles_Desert", [], ["DES"]],
	["CTRG_Retexture_airframe_04_Desert", [], ["DES"]],
    ["CTRG_Retexture_airframe_04_goggles_Desert", [], ["DES"]],
	["CTRG_Retexture_airframe_05_Desert", [], ["DES"]],
    ["CTRG_Retexture_airframe_05_goggles_Desert", [], ["DES"]],
	["CTRG_Retexture_airframe_06_Desert", [], ["DES"]],
    ["CTRG_Retexture_airframe_06_goggles_Desert", [], ["DES"]],

    ["CTRG_Retexture_airframe_01_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_airframe_01_goggles_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_airframe_02_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_airframe_02_goggles_Tundra", [], ["TUN"]],
	["CTRG_Retexture_airframe_03_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_airframe_03_goggles_Tundra", [], ["TUN"]],
	["CTRG_Retexture_airframe_04_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_airframe_04_goggles_Tundra", [], ["TUN"]],
	["CTRG_Retexture_airframe_05_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_airframe_05_goggles_Tundra", [], ["TUN"]],
	["CTRG_Retexture_airframe_06_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_airframe_06_goggles_Tundra", [], ["TUN"]],

    ["CTRG_Retexture_airframe_01_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_airframe_01_goggles_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_airframe_02_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_airframe_02_goggles_Tropic", [], ["WDL"]],
	["CTRG_Retexture_airframe_03_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_airframe_03_goggles_Tropic", [], ["WDL"]],
	["CTRG_Retexture_airframe_04_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_airframe_04_goggles_Tropic", [], ["WDL"]],
	["CTRG_Retexture_airframe_05_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_airframe_05_goggles_Tropic", [], ["WDL"]],
	["CTRG_Retexture_airframe_06_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_airframe_06_goggles_Tropic", [], ["WDL"]],

// CTRG Opscore
	["CTRG_Retexture_opscore_01_Arid", [], ["ARD"]],
    ["CTRG_Retexture_opscore_01_goggles_Arid", [], ["ARD"]],
   	["CTRG_Retexture_opscore_02_Arid", [], ["ARD"]],
    ["CTRG_Retexture_opscore_02_goggles_Arid", [], ["ARD"]],
    ["CTRG_Retexture_opscore_03_Arid", [], ["ARD"]],
    ["CTRG_Retexture_opscore_03_goggles_Arid", [], ["ARD"]],
	["CTRG_Retexture_opscore_04_Arid", [], ["ARD"]],
    ["CTRG_Retexture_opscore_04_goggles_Arid", [], ["ARD"]],
    ["CTRG_Retexture_opscore_05_Arid", [], ["ARD"]],
    ["CTRG_Retexture_opscore_05_goggles_Arid", [], ["ARD"]],
    ["CTRG_Retexture_opscore_06_Arid", [], ["ARD"]],
    ["CTRG_Retexture_opscore_06_goggles_Arid", [], ["ARD"]],

    ["CTRG_Retexture_opscore_01_Desert", [], ["DES"]],
    ["CTRG_Retexture_opscore_01_goggles_Desert", [], ["DES"]],
    ["CTRG_Retexture_opscore_02_Desert", [], ["DES"]],
    ["CTRG_Retexture_opscore_02_goggles_Desert", [], ["DES"]],
	["CTRG_Retexture_opscore_03_Desert", [], ["DES"]],
    ["CTRG_Retexture_opscore_03_goggles_Desert", [], ["DES"]],
	["CTRG_Retexture_opscore_04_Desert", [], ["DES"]],
    ["CTRG_Retexture_opscore_04_goggles_Desert", [], ["DES"]],
	["CTRG_Retexture_opscore_05_Desert", [], ["DES"]],
    ["CTRG_Retexture_opscore_05_goggles_Desert", [], ["DES"]],
	["CTRG_Retexture_opscore_06_Desert", [], ["DES"]],
    ["CTRG_Retexture_opscore_06_goggles_Desert", [], ["DES"]],

    ["CTRG_Retexture_opscore_01_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_opscore_01_goggles_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_opscore_02_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_opscore_02_goggles_Tundra", [], ["TUN"]],
	["CTRG_Retexture_opscore_03_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_opscore_03_goggles_Tundra", [], ["TUN"]],
	["CTRG_Retexture_opscore_04_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_opscore_04_goggles_Tundra", [], ["TUN"]],
	["CTRG_Retexture_opscore_05_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_opscore_05_goggles_Tundra", [], ["TUN"]],
	["CTRG_Retexture_opscore_06_Tundra", [], ["TUN"]],
    ["CTRG_Retexture_opscore_06_goggles_Tundra", [], ["TUN"]],

    ["CTRG_Retexture_opscore_01_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_opscore_01_goggles_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_opscore_02_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_opscore_02_goggles_Tropic", [], ["WDL"]],
	["CTRG_Retexture_opscore_03_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_opscore_03_goggles_Tropic", [], ["WDL"]],
	["CTRG_Retexture_opscore_04_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_opscore_04_goggles_Tropic", [], ["WDL"]],
	["CTRG_Retexture_opscore_05_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_opscore_05_goggles_Tropic", [], ["WDL"]],
	["CTRG_Retexture_opscore_06_Tropic", [], ["WDL"]],
    ["CTRG_Retexture_opscore_06_goggles_Tropic", [], ["WDL"]]
]