[
    ["CTRG_Fleece_Temperate", [], ["ARD"]],
    ["CTRG_Fleece_S_Temperate", [], ["ARD"]],
    ["CTRG_G3Field_Full_Temperate", [], ["ARD"]],
    ["CTRG_G3Field_Half_Temperate", [], ["ARD"]],
    ["CTRG_G3Field_S_Temperate", [], ["ARD"]],
    ["CTRG_G3Field_Full_Roll_Temperate", [], ["ARD"]],
    ["CTRG_G3Field_Half_Roll_Temperate", [], ["ARD"]],
    ["CTRG_G3Field_S_Roll_Temperate", [], ["ARD"]],
    ["CTRG_PCU_Full_Temperate", [], ["ARD"]],
    ["CCTRG_PCU_Half_Temperate", [], ["ARD"]],
    ["CTRG_PCU_S_Temperate", [], ["ARD"]],
    ["CTRG_Tshirt_Temperate", [], ["ARD"]],

    ["CTRG_Fleece_Desert", [], ["DES"]],
    ["CTRG_Fleece_S_Desert", [], ["DES"]],
    ["CTRG_G3Field_Full_Desert", [], ["DES"]],
    ["CTRG_G3Field_Half_Desert", [], ["DES"]],
    ["CTRG_G3Field_S_Desert", [], ["DES"]],
    ["CTRG_G3Field_Full_Roll_Desert", [], ["DES"]],
    ["CTRG_G3Field_Half_Roll_Desert", [], ["DES"]],
    ["CTRG_G3Field_S_Roll_Desert", [], ["DES"]],
    ["CTRG_PCU_Full_Desert", [], ["DES"]],
    ["CCTRG_PCU_Half_Desert", [], ["DES"]],
    ["CTRG_PCU_S_Desert", [], ["DES"]],
    ["CTRG_Tshirt_Desert", [], ["DES"]],

    ["CTRG_Fleece_Tundra", [], ["TUN"]],
    ["CTRG_Fleece_S_Tundra", [], ["TUN"]],
    ["CTRG_G3Field_Full_Tundra", [], ["TUN"]],
    ["CTRG_G3Field_Half_Tundra", [], ["TUN"]],
    ["CTRG_G3Field_S_Tundra", [], ["TUN"]],
    ["CTRG_G3Field_Full_Roll_Tundra", [], ["TUN"]],
    ["CTRG_G3Field_Half_Roll_Tundra", [], ["TUN"]],
    ["CTRG_G3Field_S_Roll_Tundra", [], ["TUN"]],
    ["CTRG_PCU_Full_Tundra", [], ["TUN"]],
    ["CCTRG_PCU_Half_Tundra", [], ["TUN"]],
    ["CTRG_PCU_S_Tundra", [], ["TUN"]],
    ["CTRG_Tshirt_Tundra", [], ["TUN"]],

    ["CTRG_Fleece_Tropic", [], ["WDL"]],
    ["CTRG_Fleece_S_Tropic", [], ["WDL"]],
    ["CTRG_G3Field_Full_Tropic", [], ["WDL"]],
    ["CTRG_G3Field_Half_Tropic", [], ["WDL"]],
    ["CTRG_G3Field_S_Tropic", [], ["WDL"]],
    ["CTRG_G3Field_Full_Roll_Tropic", [], ["WDL"]],
    ["CTRG_G3Field_Half_Roll_Tropic", [], ["WDL"]],
    ["CTRG_G3Field_S_Roll_Tropic", [], ["WDL"]],
    ["CTRG_PCU_Full_Tropic", [], ["WDL"]],
    ["CCTRG_PCU_Half_Tropic", [], ["WDL"]],
    ["CTRG_PCU_S_Tropic", [], ["WDL"]],
    ["CTRG_Tshirt_Tropic", [], ["WDL"]],

// Stealth uniform
    ["Rev_U_B_CTRG_Uniform_01_ard_F", [], ["ARD"]],
    ["Rev_U_B_CTRG_Uniform_02_ard_F", [], ["ARD"]],
    ["Rev_U_B_CTRG_Uniform_01_F", [], ["WDL"]],
    ["Rev_U_B_CTRG_Uniform_02_F", [], ["WDL"]],
    ["U_B_CTRG_Soldier_Temperate_F", [], ["ARD"]],
    ["U_B_CTRG_Soldier_3_Temperate_F", [], ["ARD"]],
    ["U_B_CTRG_Soldier_2_Temperate_F", [], ["ARD"]],
    ["U_B_CTRG_Soldier_F", [], ["WDL"]],
    ["U_B_CTRG_Soldier_3_F", [], ["WDL"]],
    ["U_B_CTRG_Soldier_2_F", [], ["WDL"]]
]
