[
// Optics
	["JCA_optic_ROS_black", [], []],
	["JCA_optic_AHO_black", [], []],
	["JCA_optic_AHO_olive", [], ["WDL", "ARD", "TUN"]],
	["JCA_optic_AHO_sand", [], ["ARD", "DES"]],
	["JCA_optic_ARO_black", [], []],
	["JCA_optic_ARO_olive", [], ["WDL", "ARD", "TUN"]],
	["JCA_optic_ARO_sand", [], ["ARD", "DES"]],
	["Aegis_optic_1p87", [], []],
	["Aegis_optic_1p87_lush", [], ["WDL", "ARD", "TUN"]],
	["Aegis_optic_1p87_snd", [], ["ARD", "DES"]],
	["JCA_optic_CRO_black", [], []],
	["JCA_optic_CRO_olive", [], ["WDL", "ARD", "TUN"]],
	["JCA_optic_CRO_sand", [], ["ARD", "DES"]],
	["optic_Holosight_blk_F", [], []],
	["optic_Holosight_khk_F", [], ["WDL", "ARD", "TUN"]],
	["optic_Holosight", [], ["ARD", "DES"]],
	["JCA_optic_ICO_black", [], []],
	["JCA_optic_ICO_olive", [], ["WDL", "ARD", "TUN"]],
	["JCA_optic_ICO_sand", [], ["ARD", "DES"]],
	["JCA_optic_IHO_black", [], []],
	["JCA_optic_IHO_olive", [], ["WDL", "ARD", "TUN"]],
	["JCA_optic_IHO_sand", [], ["ARD", "DES"]],
	["JCA_optic_IHO_black_magnifier", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], []],
	["JCA_optic_IHO_olive_magnifier", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["JCA_optic_IHO_sand_magnifier", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], ["ARD", "DES"]],
	["JCA_optic_MROS_black", [], []],
	["JCA_optic_MROS_olive", [], ["WDL", "ARD", "TUN"]],
	["JCA_optic_MROS_sand", [], ["ARD", "DES"]],
	["JCA_optic_MROS_black_magnifier", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], []],
	["JCA_optic_MROS_olive_magnifier", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["JCA_optic_MROS_sand_magnifier", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], ["ARD", "DES"]],
	["JCA_optic_AICO_black", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], []],
	["JCA_optic_AICO_olive", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["JCA_optic_AICO_sand", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], ["ARD", "DES"]],
	["JCA_optic_ACOG_black", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], []],
	["JCA_optic_ACOG_olive", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["JCA_optic_ACOG_sand", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], ["ARD", "DES"]],
	["SMA_ELCAN_SPECTER", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], []],
	["SMA_ELCAN_SPECTER_GREEN", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["SMA_ELCAN_SPECTER_TAN", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], ["ARD", "DES"]],
	["optic_MRCO", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], []],
	["optic_LRCO_blk_F", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], []],
	["optic_LRCO_snd_F", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], ["ARD", "DES"]],
	["optic_VRCO_RF", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], []],
	["optic_VRCO_khk_RF", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], ["WDL", "ARD", "TUN"]],
	["optic_VRCO_tan_RF", ["Rifleman", "Light Rifleman", "Machine Gunner", "Pointman", "Team Leader"], ["ARD", "DES"]],

// Muzzles
	["JCA_muzzle_snds_762_tactical_black", [], []],
	["JCA_muzzle_snds_762_tactical_olive", [], ["WDL", "ARD", "TUN"]],
	["JCA_muzzle_snds_762_tactical_sand", [], ["ARD", "DES"]],
	["JCA_muzzle_snds_556_advanced_black", [], []],
	["JCA_muzzle_snds_556_advanced_olive", [], ["WDL", "ARD", "TUN"]],
	["JCA_muzzle_snds_556_advanced_sand", [], ["ARD", "DES"]],
	["muzzle_snds_338_black", [], []],
	["muzzle_snds_338_green", [], ["WDL", "ARD", "TUN"]],
	["muzzle_snds_338_sand", [], ["ARD", "DES"]],
	["muzzle_snds_M", [], []],
	["muzzle_snds_L", [], []],
	["muzzle_snds_m_khk_F", [], ["WDL", "ARD", "TUN"]],
	["muzzle_snds_m_snd_F", [], ["ARD", "DES"]],
	["muzzle_snds_460", [], []],
	["Aegis_muzzle_snds_460_green", [], ["WDL", "ARD", "TUN"]],
	["Aegis_muzzle_snds_460_sand", [], ["ARD", "DES"]],
	["muzzle_snds_12Gauge_lxws", [], []],
	["aegis_muzzle_snds_pbs_762_blk", [], []],
	["aegis_muzzle_snds_pbs_762_lush", [], ["WDL", "ARD", "TUN"]],
	["aegis_muzzle_snds_pbs_762_arid", [], ["ARD", "DES"]],
	["aegis_muzzle_snds_sr25_blk", [], []],
	["aegis_muzzle_snds_sr25_lush", [], ["WDL", "ARD", "TUN"]],
	["aegis_muzzle_snds_sr25_arid", [], ["ARD", "DES"]],
	["JCA_muzzle_snds_mp5_black", [], []],
	["JCA_muzzle_snds_mp5_olive", [], ["WDL", "ARD", "TUN"]],
	["JCA_muzzle_snds_mp5_sand", [], ["ARD", "DES"]],
	["JCA_muzzle_snds_45_tactical_black", [], []],
	["JCA_muzzle_snds_45_tactical_olive", [], ["WDL", "ARD", "TUN"]],
	["JCA_muzzle_snds_45_tactical_sand", [], ["ARD", "DES"]],
	["ICM_SLX_Suppressor_F", [], []],
	["ICM_SLX_Suppressor_Arid_F", [], ["WDL", "ARD", "TUN"]],
	["ICM_SLX_Suppressor_Khaki_F", [], ["ARD", "DES"]],
	["suppressor_127x55_small_RF", [], []],
	["suppressor_127x55_small_wood_RF", [], ["WDL", "ARD", "TUN"]],
	["suppressor_127x55_small_desert_RF", [], ["ARD", "DES"]],

// Rail
	["acc_flashlight_IR", [], []],
	["ACE_SPIR", [], []],
	["acc_flashlight", [], []],
	["ACE_DBAL_A3_Green", [], []],
	["ACE_DBAL_A3_Red", [], []],
	["ACE_DBAL_A3_Red", [], []],

// Bipods
	["JCA_bipod_04_black", [], []],
	["JCA_bipod_04_olive", [], ["WDL", "ARD", "TUN"]],
	["JCA_bipod_04_sand", [], ["ARD", "DES"]]
]